namespace Stackworx.EfCoreGraphQL;

using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Stackworx.EfCoreGraphQL.Abstractions;
using Stackworx.EfCoreGraphQL.Shared;

public static class DataLoaderGenerator
{
    public static Task Generate(
        DbContext dbContext,
        string outPath,
        Mode? mode = Mode.OptOut,
        // Some types cannot be annotated and need to be manually excluded
        // E.g. Identity types
        Func<IEntityType, bool>? filter = null,
        string? ns = "Generated.DataLoaders",
        bool ci = false)
        => Generate(
            dbContext,
            outPath,
            new GenerateOptions
            {
                Mode = mode,
                Filter = filter,
                Namespace = ns ?? "Generated.DataLoaders",
                CI = ci
            });

    public static async Task Generate(
        DbContext dbContext,
        string outPath,
        GenerateOptions? options)
    {
        options ??= new GenerateOptions();

        var version = GetHotchocolateVersion();

        var mode = options.Mode;
        var filter = options.Filter;
        var ns = options.Namespace;
        var ci = options.CI;

        var model = dbContext.Model;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("//  Source: EF Core model navigations");
        sb.AppendLine("//  Style: HotChocolate [DataLoader] decorator methods");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using HotChocolate;");
        sb.AppendLine("using GreenDonut;");
        sb.AppendLine("using HotChocolate.Types;");
        sb.AppendLine();

        foreach (var entity in model.GetEntityTypes()
                     .Where(e => !e.IsOwned())
                     .OrderBy(e => e.Name))
        {
            if (entity.ShouldIgnore())
            {
                continue;
            }

            if (mode == Mode.OptIn && !entity.ShouldInclude())
            {
                continue;
            }

            // Allow user to manually exclude specific entities
            if (filter is not null && filter(entity))
            {
                continue;
            }

            Generate(dbContext, entity, sb, version);
        }

        await File.WriteAllTextAsync(outPath, sb.ToString());

        if (ci)
        {
            var hasChanges = !RunCommand("git", "diff --quiet");

            if (hasChanges)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("❌ Changes detected in generated files!");
                Console.ResetColor();
                RunCommand("git", "diff");
                System.Environment.Exit(1);
            }

            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("✅ No changes detected. Generated files are up to date.");
            Console.ResetColor();
        }
    }

    /// <summary>
    /// Generates the DataLoader file content as a string based on the provided EF Core model.
    /// This is useful for design-time scenarios (e.g. migrations scaffolding) where you want to
    /// write the output next to the EF model snapshot.
    /// </summary>
    public static string GenerateString(
        IModel model,
        GenerateOptions? options = null)
    {
        options ??= new GenerateOptions();

        var version = GetHotchocolateVersion();

        var mode = options.Mode;
        var filter = options.Filter;
        var ns = options.Namespace;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("//  Source: EF Core model navigations");
        sb.AppendLine("//  Style: HotChocolate [DataLoader] decorator methods");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using HotChocolate;");
        sb.AppendLine("using GreenDonut;");
        sb.AppendLine("using HotChocolate.Types;");
        sb.AppendLine();

        foreach (var entity in model.GetEntityTypes()
                     .Where(e => !e.IsOwned())
                     .OrderBy(e => e.Name))
        {
            if (entity.ShouldIgnore())
            {
                continue;
            }

            if (mode == Mode.OptIn && !entity.ShouldInclude())
            {
                continue;
            }

            // Allow user to manually exclude specific entities
            if (filter is not null && filter(entity))
            {
                continue;
            }

            // Design-time generation doesn't have a DbContext instance.
            // The emitters currently only need entity metadata, so we can safely pass null.
            // (Any future DbContext usage should be guarded.)
            Generate(dbContext: null!, entity, sb, version);
        }

        return sb.ToString();
    }

    private static int GetHotchocolateVersion()
    {
        const int defaultMajor = 16;

        static int? TryGetMajorFromAssemblyName(string assemblyName)
        {
            try
            {
                var asm = Assembly.Load(assemblyName);
                return asm.GetName().Version?.Major;
            }
            catch
            {
                return null;
            }
        }

        static int? TryGetMajorFromLoadedAssemblies(params string[] simpleNames)
        {
            try
            {
                foreach (var name in simpleNames)
                {
                    var match = AppDomain.CurrentDomain
                        .GetAssemblies()
                        .FirstOrDefault(a => string.Equals(a.GetName().Name, name, StringComparison.OrdinalIgnoreCase));

                    var major = match?.GetName().Version?.Major;
                    if (major is not null)
                    {
                        return major;
                    }
                }

                return null;
            }
            catch
            {
                return null;
            }
        }

        // Probe a few well-known HotChocolate assemblies.
        // We try loaded assemblies first to avoid Load() issues in some hosting scenarios.
        var candidates = new[]
        {
            "HotChocolate",
            "HotChocolate.Abstractions",
            "HotChocolate.Types",
            "HotChocolate.Execution",
            "HotChocolate.Data"
        };

        var fromLoaded = TryGetMajorFromLoadedAssemblies(candidates);
        if (fromLoaded is not null)
        {
            return fromLoaded.Value;
        }

        foreach (var candidate in candidates)
        {
            var major = TryGetMajorFromAssemblyName(candidate);
            if (major is not null)
            {
                return major.Value;
            }
        }

        return defaultMajor;
    }

    private static bool RunCommand(string fileName, string args)
    {
        var psi = new ProcessStartInfo
        {
            FileName = fileName,
            Arguments = args,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false
        };

        using var process = Process.Start(psi)!;
        process.WaitForExit();

        Console.WriteLine(process.StandardOutput.ReadToEnd());
        Console.Error.WriteLine(process.StandardError.ReadToEnd());

        return process.ExitCode == 0;
    }

    private static void Generate(DbContext dbContext, IEntityType entity, StringBuilder sb, int version)
    {
        // Skip join tables
        var pk = entity.FindPrimaryKey();
        if (pk is null)
        {
            return;
        }

        if (pk.Properties.Count > 1)
        {
            return;
        }

        sb.AppendLine($"// {entity.DisplayName()}");

        var ignoreFields = ForeignKeyIgnoreFields.Get(entity);
        var entityTypeName = TypeUtils.GetNestedQualifiedName(entity.ClrType);

        if (ignoreFields.Count > 0)
        {
            var ignoreFieldsLiteral = string.Join(", ", ignoreFields.Select(f => $"\"{f}\""));
            sb.AppendLine($"[ExtendObjectType<{entityTypeName}>(IgnoreFields = [{ignoreFieldsLiteral}])]");
        }
        else
        {
            sb.AppendLine($"[ExtendObjectType<{entityTypeName}>]");
        }

        sb.AppendLine($"public static class {entity.DisplayName()}Extensions");
        sb.AppendLine($"{{");

        if (entity.FindPrimaryKey()?.Properties.Count == 1)
        {
            var dataLoader = DataLoader.FromEntity(dbContext, entity);
            sb.Append(dataLoader.EmitComment());
            sb.AppendLine(dataLoader.Emit(version));
        }

        foreach (var navigation in entity.GetNavigations()
                     .Where(n => !n.IsEagerLoaded && !n.TargetEntityType.IsOwned())
                     .OrderBy(n => n.Name))
        {
            // TODO: warning about composite keys
            if (navigation.ForeignKey.Properties.Count > 1)
            {
                continue;
            }

            if (navigation.HasGraphQLIgnore())
            {
                continue;
            }

            // Skip dependant navigations
            if (!navigation.IsOnDependent)
            {
                var dataLoader = DataLoader.FromNavigation(dbContext, navigation);
                sb.Append(dataLoader.EmitComment());
                sb.AppendLine(dataLoader.Emit(version));
            }

            var field = FieldExtension.FromNavigation(dbContext, navigation);
            sb.Append(field.EmitComment());
            sb.AppendLine(field.Emit());
        }

        foreach (var navigation in entity.GetSkipNavigations()
                     .Where(n => !n.IsEagerLoaded)
                     .OrderBy(n => n.Name))
        {
            if (navigation.HasGraphQLIgnore())
            {
                continue;
            }

            // We can only generate a correct many-to-many data loader when the skip navigation has a CLR-backed inverse
            // (either a property or a field). Without an inverse member, EF can still model the relationship, but we
            // can't reliably:
            //  - project the "parent" key from the join, and
            //  - select/shape the "child" collection for lookup,
            // because our emission code uses the inverse member name to build the SelectMany() expression.
            //
            // Example:
            //   class Post { public int Id { get; set; } public ICollection<Tag> Tags { get; set; } }
            //   class Tag  { public int Id { get; set; } public ICollection<Post> Posts { get; set; } }
            //
            // The generated loader needs the inverse navigation (Tag.Posts) to map parent ids to children:
            //   [DataLoader]
            //   public static async Task<ILookup<int, Tag>> TagsByPosts(
            //       IReadOnlyList<int> keys,
            //       AppDbContext context,
            //       CancellationToken ct)
            //   {
            //       var pairs = await context.Set<Tag>()
            //           .Where(t => t.Posts.Any(p => keys.Contains(p.Id)))
            //           .SelectMany(tag => tag.Posts.Select(post => new { post.Id, Child = tag }))
            //           .AsNoTracking()
            //           .ToListAsync(ct);
            //
            //       return pairs.ToLookup(e => e.Id, x => x.Child);
            //   }
            //
            // If the inverse doesn't exist, we skip emitting this loader/field extension to avoid generating code that
            // won't compile or will behave incorrectly.
            if (navigation.Inverse.FieldInfo is null && navigation.Inverse.PropertyInfo is null)
            {
                continue;
            }
            
            // Skip dependant navigations
            if (!navigation.IsOnDependent)
            {
                // TODO: emit extension
                var manyToMany = ManyToMany.FromNavigation(dbContext, navigation);
                sb.AppendLine(manyToMany.EmitDataLoader());
                sb.AppendLine(manyToMany.EmitFieldExtension());
            }
        }

        sb.AppendLine($"}}");
        sb.AppendLine();
    }
}