namespace Stackworx.EfCoreGraphQL;

using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Stackworx.EfCoreGraphQL.Abstractions;
using Stackworx.EfCoreGraphQL.Shared;

public static class DataLoaderGenerator
{
    public static Task Generate(
        DbContext dbContext,
        string outPath,
        Mode? mode = Mode.OptOut,
        // Some types cannot be annotated and need to be manually excluded
        // E.g. Identity types
        Func<IEntityType, bool>? filter = null,
        string? ns = GenerateOptions.DefaultNamespace,
        bool ci = false)
        => Generate(
            dbContext,
            outPath,
            new GenerateOptions
            {
                Mode = mode,
                Filter = filter,
                Namespace = ns,
                CI = ci
            });

    public static async Task Generate(
        DbContext dbContext,
        string outPath,
        GenerateOptions? options)
    {
        options ??= new GenerateOptions();

        var ci = options.CI;

        await File.WriteAllTextAsync(outPath, BuildSource(dbContext.Model, dbContext.GetType(), options));

        if (ci)
        {
            var hasChanges = !RunCommand("git", "diff --quiet");

            if (hasChanges)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("❌ Changes detected in generated files!");
                Console.ResetColor();
                RunCommand("git", "diff");
                System.Environment.Exit(1);
            }

            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("✅ No changes detected. Generated files are up to date.");
            Console.ResetColor();
        }
    }

    /// <summary>
    /// Generates the DataLoader file content as a string based on the provided EF Core model.
    /// This is useful for design-time scenarios (e.g. migrations scaffolding) where you want to
    /// write the output next to the EF model snapshot.
    /// </summary>
    public static string GenerateString(
        IModel model,
        Type contextType,
        GenerateOptions? options = null)
        => BuildSource(model, contextType, options ?? new GenerateOptions());

    private static string BuildSource(
        IModel model,
        Type contextType,
        GenerateOptions options)
    {
        var version = GetHotchocolateVersion();

        var mode = options.Mode;
        var filter = options.Filter;
        var ns = options.Namespace ?? GenerateOptions.DefaultNamespace;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("//  Source: EF Core model navigations");
        sb.AppendLine("//  Style: HotChocolate [DataLoader] decorator methods");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using HotChocolate;");
        sb.AppendLine("using GreenDonut;");
        sb.AppendLine("using HotChocolate.Types;");
        sb.AppendLine();

        // HotChocolate emits one DataLoader class per [DataLoader] method name, and every method we
        // generate lands in the same namespace. The same loader can be reachable from two entities, so
        // names are tracked across the whole run to keep each one emitted exactly once.
        var emittedLoaders = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var entity in model.GetEntityTypes().OrderBy(e => e.Name))
        {
            if (!GenerationPolicy.GeneratesFor(entity, mode, filter))
            {
                continue;
            }

            Generate(contextType, entity, sb, version, emittedLoaders, options.IgnoreForeignKeyFields);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Emits a data loader unless one with the same name has already been emitted.
    /// </summary>
    /// <remarks>
    /// A loader name is reachable from more than one entity when a dependent's primary key is also its
    /// foreign key to the principal: the principal's navigation loader and the dependent's primary-key
    /// loader are keyed on the same property, so both resolve to the same name and the same query.
    /// Field extensions reference the loader interface by name, so skipping the repeat is safe.
    /// </remarks>
    private static void AppendLoader(
        StringBuilder sb,
        Dictionary<string, string> emittedLoaders,
        string loaderName,
        string comment,
        string code)
    {
        if (emittedLoaders.TryGetValue(loaderName, out var existing))
        {
            if (string.Equals(existing, code, StringComparison.Ordinal))
            {
                return;
            }

            // Two different queries want the same name. Emitting both cannot compile, and silently
            // dropping one would leave field extensions bound to the wrong loader.
            throw new InvalidOperationException(
                $"Two different data loaders were generated with the name '{loaderName}'. " +
                $"Exclude one of the navigations with [{nameof(EFCoreGraphQLIgnoreAttribute)}] or rename it.");
        }

        emittedLoaders[loaderName] = code;
        sb.Append(comment);
        sb.AppendLine(code);
    }

    private static int GetHotchocolateVersion()
    {
        const int defaultMajor = 16;

        static int? TryGetMajorFromAssemblyName(string assemblyName)
        {
            try
            {
                var asm = Assembly.Load(assemblyName);
                return asm.GetName().Version?.Major;
            }
            catch
            {
                return null;
            }
        }

        static int? TryGetMajorFromLoadedAssemblies(params string[] simpleNames)
        {
            try
            {
                foreach (var name in simpleNames)
                {
                    var match = AppDomain.CurrentDomain
                        .GetAssemblies()
                        .FirstOrDefault(a => string.Equals(a.GetName().Name, name, StringComparison.OrdinalIgnoreCase));

                    var major = match?.GetName().Version?.Major;
                    if (major is not null)
                    {
                        return major;
                    }
                }

                return null;
            }
            catch
            {
                return null;
            }
        }

        // Probe a few well-known HotChocolate assemblies.
        // We try loaded assemblies first to avoid Load() issues in some hosting scenarios.
        var candidates = new[]
        {
            "HotChocolate",
            "HotChocolate.Abstractions",
            "HotChocolate.Types",
            "HotChocolate.Execution",
            "HotChocolate.Data"
        };

        var fromLoaded = TryGetMajorFromLoadedAssemblies(candidates);
        if (fromLoaded is not null)
        {
            return fromLoaded.Value;
        }

        foreach (var candidate in candidates)
        {
            var major = TryGetMajorFromAssemblyName(candidate);
            if (major is not null)
            {
                return major.Value;
            }
        }

        return defaultMajor;
    }

    private static bool RunCommand(string fileName, string args)
    {
        var psi = new ProcessStartInfo
        {
            FileName = fileName,
            Arguments = args,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false
        };

        using var process = Process.Start(psi)!;
        process.WaitForExit();

        Console.WriteLine(process.StandardOutput.ReadToEnd());
        Console.Error.WriteLine(process.StandardError.ReadToEnd());

        return process.ExitCode == 0;
    }

    private static void Generate(
        Type dbContextClass,
        IEntityType entity,
        StringBuilder sb,
        int version,
        Dictionary<string, string> emittedLoaders,
        bool ignoreForeignKeyFields)
    {
        sb.AppendLine($"// {entity.DisplayName()}");

        var ignoreFields = ignoreForeignKeyFields
            ? ForeignKeyIgnoreFields.Get(entity)
            : [];
        var entityTypeName = TypeUtils.GetNestedQualifiedName(entity.ClrType);

        if (ignoreFields.Count > 0)
        {
            var ignoreFieldsLiteral = string.Join(", ", ignoreFields.Select(f => $"\"{f}\""));
            sb.AppendLine($"[ExtendObjectType<{entityTypeName}>(IgnoreFields = [{ignoreFieldsLiteral}])]");
        }
        else
        {
            sb.AppendLine($"[ExtendObjectType<{entityTypeName}>]");
        }

        sb.AppendLine($"public static class {TypeUtils.GetIdentifierName(entity.ClrType)}Extensions");
        sb.AppendLine($"{{");

        var primaryKeyLoader = DataLoader.FromEntity(dbContextClass, entity);
        AppendLoader(
            sb,
            emittedLoaders,
            primaryKeyLoader.LoaderName,
            primaryKeyLoader.EmitComment(),
            primaryKeyLoader.Emit(version));

        foreach (var navigation in entity.GetNavigations().OrderBy(n => n.Name))
        {
            // TODO: warning about composite keys
            if (!GenerationPolicy.GeneratesFor(navigation))
            {
                continue;
            }

            // Skip dependant navigations
            var dataLoader = navigation.IsOnDependent
                ? null
                : DataLoader.FromNavigation(dbContextClass, navigation);

            var field = FieldExtension.FromNavigation(dbContextClass, navigation);

            if (dataLoader is not null)
            {
                AppendLoader(sb, emittedLoaders, dataLoader.LoaderName, dataLoader.EmitComment(), dataLoader.Emit(version));
            }

            sb.Append(field.EmitComment());
            sb.AppendLine(field.Emit());
        }

        foreach (var navigation in entity.GetSkipNavigations().OrderBy(n => n.Name))
        {
            if (!GenerationPolicy.GeneratesFor(navigation))
            {
                continue;
            }

            // TODO: emit extension
            var manyToMany = ManyToMany.FromNavigation(dbContextClass, navigation);
            AppendLoader(sb, emittedLoaders, manyToMany.LoaderName, string.Empty, manyToMany.EmitDataLoader());
            sb.AppendLine(manyToMany.EmitFieldExtension());
        }

        sb.AppendLine($"}}");
        sb.AppendLine();
    }
}