// <auto-generated>
#nullable enable
#pragma warning disable
//  Source: EF Core model navigations
//  Style: HotChocolate [DataLoader] decorator methods
// </auto-generated>

namespace Sample.DesignTime.Migrations.Generated.DataLoaders;
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using HotChocolate;
using GreenDonut;
using HotChocolate.Types;

// Author
[ExtendObjectType<Sample.DesignTime.Data.Author>]
public static class AuthorExtensions
{
    /// <summary>
    /// Primary Key Data Loader for <see cref="Sample.DesignTime.Data.Author"/>
    /// </summary>
    [DataLoader]
    public static async Task<IDictionary<int, Sample.DesignTime.Data.Author>> AuthorById(
        IReadOnlyList<int> keys,
        Sample.DesignTime.Data.AppDbContext context,
        CancellationToken ct)
    {
        return await context.Set<Sample.DesignTime.Data.Author>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.Id))
            .ToDictionaryAsync(e => e.Id, ct);
    }

    /// <summary>
    /// Navigation Data Loader for <see cref="Sample.DesignTime.Data.Book.Author"/>
    /// </summary>
    [DataLoader]
    public static async Task<ILookup<int, Sample.DesignTime.Data.Book>> BooksByAuthorId(
        IReadOnlyList<int> keys,
        Sample.DesignTime.Data.AppDbContext context,
        CancellationToken ct)
    {
        var items = await context.Set<Sample.DesignTime.Data.Book>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.AuthorId))
            .ToListAsync(ct);

        return items.ToLookup(e => e.AuthorId);
    }

    /// <summary>
    /// GraphQL Field Override for <see cref="Sample.DesignTime.Data.Author.Books"/>
    /// </summary>
    public static async Task<IList<Sample.DesignTime.Data.Book>> GetBooksAsync(
        [Parent] Sample.DesignTime.Data.Author parent,
        IBooksByAuthorIdDataLoader loader,
        CancellationToken ct)
    {
        return await loader.LoadAsync(parent.Id, ct);
    }

}

// Book
[ExtendObjectType<Sample.DesignTime.Data.Book>(IgnoreFields = ["authorId"])]
public static class BookExtensions
{
    /// <summary>
    /// Primary Key Data Loader for <see cref="Sample.DesignTime.Data.Book"/>
    /// </summary>
    [DataLoader]
    public static async Task<IDictionary<int, Sample.DesignTime.Data.Book>> BookById(
        IReadOnlyList<int> keys,
        Sample.DesignTime.Data.AppDbContext context,
        CancellationToken ct)
    {
        return await context.Set<Sample.DesignTime.Data.Book>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.Id))
            .ToDictionaryAsync(e => e.Id, ct);
    }

    /// <summary>
    /// GraphQL Field Override for <see cref="Sample.DesignTime.Data.Book.Author"/>
    /// </summary>
    public static async Task<Sample.DesignTime.Data.Author> GetAuthorAsync(
        [Parent] Sample.DesignTime.Data.Book parent,
        IAuthorByIdDataLoader loader,
        CancellationToken ct)
    {
        return await loader.LoadAsync(parent.AuthorId, ct);
    }

}

