// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stackworx.EfCoreGraphQL.Tests.Data;

#nullable disable

namespace Sample.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260121191325_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("PostTag", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTags", (string)null);
                });

            modelBuilder.Entity("PostTag1", b =>
                {
                    b.Property<int>("PostsShadowId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsShadowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostsShadowId", "TagsShadowId");

                    b.HasIndex("TagsShadowId");

                    b.ToTable("PostTag1");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Enrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Grade")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Order", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Year", "Number");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.OrderItem", b =>
                {
                    b.Property<int>("OrderYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OrderYear", "OrderNumber", "LineNo");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Passport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Passports");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.HasOne("Stackworx.EfCoreGraphQL.Tests.Data.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stackworx.EfCoreGraphQL.Tests.Data.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PostTag1", b =>
                {
                    b.HasOne("Stackworx.EfCoreGraphQL.Tests.Data.Post", null)
                        .WithMany()
                        .HasForeignKey("PostsShadowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stackworx.EfCoreGraphQL.Tests.Data.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsShadowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Book", b =>
                {
                    b.HasOne("Stackworx.EfCoreGraphQL.Tests.Data.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Comment", b =>
                {
                    b.HasOne("Stackworx.EfCoreGraphQL.Tests.Data.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Enrollment", b =>
                {
                    b.HasOne("Stackworx.EfCoreGraphQL.Tests.Data.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stackworx.EfCoreGraphQL.Tests.Data.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.OrderItem", b =>
                {
                    b.HasOne("Stackworx.EfCoreGraphQL.Tests.Data.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderYear", "OrderNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Passport", b =>
                {
                    b.HasOne("Stackworx.EfCoreGraphQL.Tests.Data.Person", "Person")
                        .WithOne("Passport")
                        .HasForeignKey("Stackworx.EfCoreGraphQL.Tests.Data.Passport", "PersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.UserProfile", b =>
                {
                    b.HasOne("Stackworx.EfCoreGraphQL.Tests.Data.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Stackworx.EfCoreGraphQL.Tests.Data.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Person", b =>
                {
                    b.Navigation("Passport");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Stackworx.EfCoreGraphQL.Tests.Data.User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
