// <auto-generated>
#nullable enable
#pragma warning disable
//  Source: EF Core model navigations
//  Style: HotChocolate [DataLoader] decorator methods
// </auto-generated>

namespace Generated.DataLoaders;
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using HotChocolate;
using GreenDonut;
using HotChocolate.Types;

// Author
[ExtendObjectType<Stackworx.EfCoreGraphQL.Tests.Data.Author>]
public static class AuthorExtensions
{
    /// <summary>
    /// Primary Key Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Author"/>
    /// </summary>
    [DataLoader]
    public static async Task<IDictionary<int, Stackworx.EfCoreGraphQL.Tests.Data.Author>> AuthorById(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        return await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Author>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.Id))
            .ToDictionaryAsync(e => e.Id, ct);
    }

    /// <summary>
    /// Navigation Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Book.Author"/>
    /// </summary>
    [DataLoader]
    public static async Task<ILookup<int, Stackworx.EfCoreGraphQL.Tests.Data.Book>> BooksByAuthorId(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        var items = await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Book>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.AuthorId))
            .ToListAsync(ct);

        return items.ToLookup(e => e.AuthorId);
    }

    /// <summary>
    /// GraphQL Field Override for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Author.Books"/>
    /// </summary>
    public static async Task<IList<Stackworx.EfCoreGraphQL.Tests.Data.Book>> GetBooksAsync(
        [Parent] Stackworx.EfCoreGraphQL.Tests.Data.Author parent,
        IBooksByAuthorIdDataLoader loader,
        CancellationToken ct)
    {
        return await loader.LoadAsync(parent.Id, ct);
    }

}

// Book
[ExtendObjectType<Stackworx.EfCoreGraphQL.Tests.Data.Book>(IgnoreFields = ["authorId"])]
public static class BookExtensions
{
    /// <summary>
    /// Primary Key Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Book"/>
    /// </summary>
    [DataLoader]
    public static async Task<IDictionary<int, Stackworx.EfCoreGraphQL.Tests.Data.Book>> BookById(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        return await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Book>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.Id))
            .ToDictionaryAsync(e => e.Id, ct);
    }

    /// <summary>
    /// GraphQL Field Override for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Book.Author"/>
    /// </summary>
    public static async Task<Stackworx.EfCoreGraphQL.Tests.Data.Author> GetAuthorAsync(
        [Parent] Stackworx.EfCoreGraphQL.Tests.Data.Book parent,
        IAuthorByIdDataLoader loader,
        CancellationToken ct)
    {
        return await loader.LoadAsync(parent.AuthorId, ct);
    }

}

// Comment
[ExtendObjectType<Stackworx.EfCoreGraphQL.Tests.Data.Comment>(IgnoreFields = ["postId"])]
public static class CommentExtensions
{
    /// <summary>
    /// Primary Key Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Comment"/>
    /// </summary>
    [DataLoader]
    public static async Task<IDictionary<int, Stackworx.EfCoreGraphQL.Tests.Data.Comment>> CommentById(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        return await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Comment>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.Id))
            .ToDictionaryAsync(e => e.Id, ct);
    }

    /// <summary>
    /// GraphQL Field Override for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Comment.Post"/>
    /// </summary>
    public static async Task<Stackworx.EfCoreGraphQL.Tests.Data.Post?> GetPostAsync(
        [Parent] Stackworx.EfCoreGraphQL.Tests.Data.Comment parent,
        IPostByIdDataLoader loader,
        CancellationToken ct)
    {
        if (parent.PostId is not null)
        {
            return await loader.LoadAsync(parent.PostId.Value, ct);
        }

        return null;
    }

}

// Course
[ExtendObjectType<Stackworx.EfCoreGraphQL.Tests.Data.Course>]
public static class CourseExtensions
{
    /// <summary>
    /// Primary Key Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Course"/>
    /// </summary>
    [DataLoader]
    public static async Task<IDictionary<int, Stackworx.EfCoreGraphQL.Tests.Data.Course>> CourseById(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        return await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Course>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.Id))
            .ToDictionaryAsync(e => e.Id, ct);
    }

    /// <summary>
    /// Navigation Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Enrollment.Course"/>
    /// </summary>
    [DataLoader]
    public static async Task<ILookup<int, Stackworx.EfCoreGraphQL.Tests.Data.Enrollment>> EnrollmentsByCourseId(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        var items = await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Enrollment>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.CourseId))
            .ToListAsync(ct);

        return items.ToLookup(e => e.CourseId);
    }

    /// <summary>
    /// GraphQL Field Override for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Course.Enrollments"/>
    /// </summary>
    public static async Task<IList<Stackworx.EfCoreGraphQL.Tests.Data.Enrollment>> GetEnrollmentsAsync(
        [Parent] Stackworx.EfCoreGraphQL.Tests.Data.Course parent,
        IEnrollmentsByCourseIdDataLoader loader,
        CancellationToken ct)
    {
        return await loader.LoadAsync(parent.Id, ct);
    }

}

// Passport
[ExtendObjectType<Stackworx.EfCoreGraphQL.Tests.Data.Passport>(IgnoreFields = ["personId"])]
public static class PassportExtensions
{
    /// <summary>
    /// Primary Key Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Passport"/>
    /// </summary>
    [DataLoader]
    public static async Task<IDictionary<int, Stackworx.EfCoreGraphQL.Tests.Data.Passport>> PassportById(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        return await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Passport>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.Id))
            .ToDictionaryAsync(e => e.Id, ct);
    }

    /// <summary>
    /// GraphQL Field Override for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Passport.Person"/>
    /// </summary>
    public static async Task<Stackworx.EfCoreGraphQL.Tests.Data.Person?> GetPersonAsync(
        [Parent] Stackworx.EfCoreGraphQL.Tests.Data.Passport parent,
        IPersonByIdDataLoader loader,
        CancellationToken ct)
    {
        if (parent.PersonId is not null)
        {
            return await loader.LoadAsync(parent.PersonId.Value, ct);
        }

        return null;
    }

}

// Person
[ExtendObjectType<Stackworx.EfCoreGraphQL.Tests.Data.Person>]
public static class PersonExtensions
{
    /// <summary>
    /// Primary Key Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Person"/>
    /// </summary>
    [DataLoader]
    public static async Task<IDictionary<int, Stackworx.EfCoreGraphQL.Tests.Data.Person>> PersonById(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        return await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Person>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.Id))
            .ToDictionaryAsync(e => e.Id, ct);
    }

    /// <summary>
    /// Navigation Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Passport.Person"/>
    /// </summary>
    [DataLoader]
    public static async Task<IDictionary<int, Stackworx.EfCoreGraphQL.Tests.Data.Passport>> PassportByPersonId(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        return await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Passport>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.PersonId!.Value))
            .ToDictionaryAsync(e => e.PersonId!.Value, ct);
    }

    /// <summary>
    /// GraphQL Field Override for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Person.Passport"/>
    /// </summary>
    public static async Task<Stackworx.EfCoreGraphQL.Tests.Data.Passport?> GetPassportAsync(
        [Parent] Stackworx.EfCoreGraphQL.Tests.Data.Person parent,
        IPassportByPersonIdDataLoader loader,
        CancellationToken ct)
    {
        return await loader.LoadAsync(parent.Id, ct);
    }

}

// Post
[ExtendObjectType<Stackworx.EfCoreGraphQL.Tests.Data.Post>]
public static class PostExtensions
{
    /// <summary>
    /// Primary Key Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Post"/>
    /// </summary>
    [DataLoader]
    public static async Task<IDictionary<int, Stackworx.EfCoreGraphQL.Tests.Data.Post>> PostById(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        return await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Post>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.Id))
            .ToDictionaryAsync(e => e.Id, ct);
    }

    /// <summary>
    /// Navigation Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Comment.Post"/>
    /// </summary>
    [DataLoader]
    public static async Task<ILookup<int, Stackworx.EfCoreGraphQL.Tests.Data.Comment>> CommentsByPostId(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        var items = await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Comment>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.PostId!.Value))
            .ToListAsync(ct);

        return items.ToLookup(e => e.PostId!.Value);
    }

    /// <summary>
    /// GraphQL Field Override for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Post.Comments"/>
    /// </summary>
    public static async Task<IList<Stackworx.EfCoreGraphQL.Tests.Data.Comment>> GetCommentsAsync(
        [Parent] Stackworx.EfCoreGraphQL.Tests.Data.Post parent,
        ICommentsByPostIdDataLoader loader,
        CancellationToken ct)
    {
        return await loader.LoadAsync(parent.Id, ct);
    }

    /// <summary>
    /// Skip Navigation Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Tag.Posts"/>
    /// </summary>
    [DataLoader]
    public static async Task<ILookup<int, Stackworx.EfCoreGraphQL.Tests.Data.Tag>> TagsByPosts(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        var pairs = await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Tag>()
            .Where(e => e.Posts.Any(p => keys.Contains(p.Id)))
            .SelectMany(child => child.Posts.Select(parent => new { parent.Id, Child = child }))
            .AsNoTracking()
            .ToListAsync(ct);

        return pairs.ToLookup(e => e.Id, x => x.Child);
    }

    /// <summary>
    /// GraphQL Field Override for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Post.Tags"/>
    /// </summary>
    public static async Task<Stackworx.EfCoreGraphQL.Tests.Data.Tag[]> GetTagsAsync(
        [Parent] Stackworx.EfCoreGraphQL.Tests.Data.Post parent,
        ITagsByPostsDataLoader loader,
        CancellationToken ct)
    {
        return await loader.LoadAsync(parent.Id, ct);
    }

}

// Student
[ExtendObjectType<Stackworx.EfCoreGraphQL.Tests.Data.Student>]
public static class StudentExtensions
{
    /// <summary>
    /// Primary Key Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Student"/>
    /// </summary>
    [DataLoader]
    public static async Task<IDictionary<int, Stackworx.EfCoreGraphQL.Tests.Data.Student>> StudentById(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        return await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Student>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.Id))
            .ToDictionaryAsync(e => e.Id, ct);
    }

    /// <summary>
    /// Navigation Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Enrollment.Student"/>
    /// </summary>
    [DataLoader]
    public static async Task<ILookup<int, Stackworx.EfCoreGraphQL.Tests.Data.Enrollment>> EnrollmentsByStudentId(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        var items = await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Enrollment>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.StudentId))
            .ToListAsync(ct);

        return items.ToLookup(e => e.StudentId);
    }

    /// <summary>
    /// GraphQL Field Override for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Student.Enrollments"/>
    /// </summary>
    public static async Task<IList<Stackworx.EfCoreGraphQL.Tests.Data.Enrollment>> GetEnrollmentsAsync(
        [Parent] Stackworx.EfCoreGraphQL.Tests.Data.Student parent,
        IEnrollmentsByStudentIdDataLoader loader,
        CancellationToken ct)
    {
        return await loader.LoadAsync(parent.Id, ct);
    }

}

// Tag
[ExtendObjectType<Stackworx.EfCoreGraphQL.Tests.Data.Tag>]
public static class TagExtensions
{
    /// <summary>
    /// Primary Key Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Tag"/>
    /// </summary>
    [DataLoader]
    public static async Task<IDictionary<int, Stackworx.EfCoreGraphQL.Tests.Data.Tag>> TagById(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        return await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Tag>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.Id))
            .ToDictionaryAsync(e => e.Id, ct);
    }

    /// <summary>
    /// Skip Navigation Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Post.Tags"/>
    /// </summary>
    [DataLoader]
    public static async Task<ILookup<int, Stackworx.EfCoreGraphQL.Tests.Data.Post>> PostsByTags(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        var pairs = await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Post>()
            .Where(e => e.Tags.Any(p => keys.Contains(p.Id)))
            .SelectMany(child => child.Tags.Select(parent => new { parent.Id, Child = child }))
            .AsNoTracking()
            .ToListAsync(ct);

        return pairs.ToLookup(e => e.Id, x => x.Child);
    }

    /// <summary>
    /// GraphQL Field Override for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Tag.Posts"/>
    /// </summary>
    public static async Task<Stackworx.EfCoreGraphQL.Tests.Data.Post[]> GetPostsAsync(
        [Parent] Stackworx.EfCoreGraphQL.Tests.Data.Tag parent,
        IPostsByTagsDataLoader loader,
        CancellationToken ct)
    {
        return await loader.LoadAsync(parent.Id, ct);
    }

    /// <summary>
    /// Skip Navigation Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Post.TagsShadow"/>
    /// </summary>
    [DataLoader]
    public static async Task<ILookup<int, Stackworx.EfCoreGraphQL.Tests.Data.Post>> PostsShadowByTagsShadow(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        var pairs = await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.Post>()
            .Where(e => e.TagsShadow.Any(p => keys.Contains(p.Id)))
            .SelectMany(child => child.TagsShadow.Select(parent => new { parent.Id, Child = child }))
            .AsNoTracking()
            .ToListAsync(ct);

        return pairs.ToLookup(e => e.Id, x => x.Child);
    }

    /// <summary>
    /// GraphQL Field Override for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.Tag.PostsShadow"/>
    /// </summary>
    public static async Task<Stackworx.EfCoreGraphQL.Tests.Data.Post[]> GetPostsShadowAsync(
        [Parent] Stackworx.EfCoreGraphQL.Tests.Data.Tag parent,
        IPostsShadowByTagsShadowDataLoader loader,
        CancellationToken ct)
    {
        return await loader.LoadAsync(parent.Id, ct);
    }

}

// User
[ExtendObjectType<Stackworx.EfCoreGraphQL.Tests.Data.User>]
public static class UserExtensions
{
    /// <summary>
    /// Primary Key Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.User"/>
    /// </summary>
    [DataLoader]
    public static async Task<IDictionary<int, Stackworx.EfCoreGraphQL.Tests.Data.User>> UserById(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        return await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.User>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.Id))
            .ToDictionaryAsync(e => e.Id, ct);
    }

    /// <summary>
    /// Navigation Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.UserProfile.User"/>
    /// </summary>
    [DataLoader]
    public static async Task<IDictionary<int, Stackworx.EfCoreGraphQL.Tests.Data.UserProfile>> UserProfileByUserId(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        return await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.UserProfile>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.UserId))
            .ToDictionaryAsync(e => e.UserId, ct);
    }

    /// <summary>
    /// GraphQL Field Override for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.User.Profile"/>
    /// </summary>
    public static async Task<Stackworx.EfCoreGraphQL.Tests.Data.UserProfile> GetProfileAsync(
        [Parent] Stackworx.EfCoreGraphQL.Tests.Data.User parent,
        IUserProfileByUserIdDataLoader loader,
        CancellationToken ct)
    {
        return await loader.LoadAsync(parent.Id, ct);
    }

}

// UserProfile
[ExtendObjectType<Stackworx.EfCoreGraphQL.Tests.Data.UserProfile>(IgnoreFields = ["userId"])]
public static class UserProfileExtensions
{
    /// <summary>
    /// Primary Key Data Loader for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.UserProfile"/>
    /// </summary>
    [DataLoader]
    public static async Task<IDictionary<int, Stackworx.EfCoreGraphQL.Tests.Data.UserProfile>> UserProfileById(
        IReadOnlyList<int> keys,
        Stackworx.EfCoreGraphQL.Tests.Data.AppDbContext context,
        CancellationToken ct)
    {
        return await context.Set<Stackworx.EfCoreGraphQL.Tests.Data.UserProfile>()
            .AsNoTracking()
            .Where(e => keys.Contains(e.Id))
            .ToDictionaryAsync(e => e.Id, ct);
    }

    /// <summary>
    /// GraphQL Field Override for <see cref="Stackworx.EfCoreGraphQL.Tests.Data.UserProfile.User"/>
    /// </summary>
    public static async Task<Stackworx.EfCoreGraphQL.Tests.Data.User> GetUserAsync(
        [Parent] Stackworx.EfCoreGraphQL.Tests.Data.UserProfile parent,
        IUserByIdDataLoader loader,
        CancellationToken ct)
    {
        return await loader.LoadAsync(parent.UserId, ct);
    }

}

