<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.3" />
        <PackageReference Include="HotChocolate" Version="15.1.11" />
        <PackageReference Include="HotChocolate.AspNetCore" Version="15.1.11" />
        <PackageReference Include="HotChocolate.Data.EntityFramework" Version="15.1.11" />
        <PackageReference Include="HotChocolate.Types.Analyzers" Version="15.1.11" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Stackworx.EfCoreGraphQL\Stackworx.EfCoreGraphQL.csproj" />
    </ItemGroup>

</Project>
